theme: jekyll-theme-minimal
title: Joshua Wolff - Electrical Engineer
description: Electrical engineering student seeking a Summer 2026 internship in power systems. Brings three years of
experience in technical research and warranty management. Skilled in technical writing and collaborative
problem-solving, with a strong interest in advancing power reliability, grid technologies, and energy
systems innovation
